[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --strict-markers -ra
markers =
    ui: UI тесты интерфейса saucedemo
    api: API проверки сервиса reqres
filterwarnings =
    ignore::DeprecationWarning